# Generated by Django 5.1.5 on 2025-01-19 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ru_processed_image', models.ImageField(blank=True, null=True, upload_to='processed_images/')),
                ('en_processed_image', models.ImageField(blank=True, null=True, upload_to='processed_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_object_type', models.CharField(max_length=100)),
                ('en_object_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('image_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='object_detection.imagefeed')),
            ],
        ),
    ]
